/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiModuloMenu;

import ClasesTablas.Item;
import ControladorClasesTablas.ItemJpaController;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Moni
 */
public class PanelModificarItem extends javax.swing.JPanel {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("LCPU"); // LCPU es el nombre de nuestra unidad de persistencia
    /**
     * Creates new form JPanellModificar
     */
    public PanelModificarItem() {
        initComponents();
        this.jtTablaModificarItem.setModel(new defaultModelItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaModificarItem = new javax.swing.JTable();
        jlContinuarModificarItem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(752, 662));

        jtTablaModificarItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.Identificacion", "Nombre", "Precio", "Categoria", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTablaModificarItem);

        jlContinuarModificarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonContinuar.png"))); // NOI18N
        jlContinuarModificarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlContinuarModificarItemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jlContinuarModificarItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlContinuarModificarItem)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlContinuarModificarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlContinuarModificarItemMouseClicked
        
        if(this.jtTablaModificarItem.getSelectedRow() != -1){
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        
        //EntityManagerFactory emf = Persistence.createEntityManagerFactory("LCPU"); // LCPU es el nombre de nuestra unidad de persistencia
        ItemJpaController dao = new ItemJpaController(emf);
        
        PanelRealizarModificacionItem rm = new PanelRealizarModificacionItem();
        
        int idItem = Integer.parseInt(String.valueOf(jtTablaModificarItem.getValueAt(jtTablaModificarItem.getSelectedRow(), 0)));
        
        Item item = dao.findItem(idItem);
        if(!(item.getFoto() == null))
        {    
        rm.jlFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource(item.getFoto())));
        }
        else
        {
         rm.jlFoto.setIcon(null);
        }    
        rm.jtfID.setText(item.getIdItem().toString());
        rm.jtfNombre.setText(item.getNombre());
        rm.jtfPrecio.setText(Integer.toString(item.getPrecio()));
        rm.jcbCategoria.setSelectedItem(item.getCategoria());
        rm.jtaDescripcion1.setText(item.getDescripcion());
        
        rm.setSize(752, 686);
        this.add(rm);
        emf.close();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un item primero por favor");
        }
    }//GEN-LAST:event_jlContinuarModificarItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlContinuarModificarItem;
    public javax.swing.JTable jtTablaModificarItem;
    // End of variables declaration//GEN-END:variables

    public LinkedList<Item> listaItems(){
        LinkedList<Item> listaItems = new LinkedList<>();
        ItemJpaController ijc = new ItemJpaController(emf);
        List<Item> lista = ijc.findItemEntities();
        
        for (Item item : lista) {
            if(item.getEstado().equals("Activo")){
                listaItems.add(item);
            }
        }
        return listaItems;
    }
    
    public class defaultModelItem extends AbstractTableModel{
        
        
        List<Item> listaitem = listaItems();
        
        
        @Override
        public int getRowCount() {
            return listaitem.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public String getColumnName(int column) {
            switch(column){
                case 0: 
                    return "Id"; 
                case 1: 
                    return "Nombre";
                case 2: 
                    return "Precio";
                case 3: 
                    return "Categoria";
                case 4: 
                    return "Descripcion"; 
            }
            return "";
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            
            Item item = listaitem.get(rowIndex);
            
            switch(columnIndex){
                case 0: return item.getIdItem();
                case 1: return item.getNombre();
                case 2: return item.getPrecio();
                case 3: return item.getCategoria();
                case 4: return item.getDescripcion();
            }
            return "";
        }
    }
    

}
