

package GuiModuloPersonal;

import ClasesTablas.Empleado;
import ControladorClasesTablas.EmpleadoJpaController;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;

/**
 *
 * 
 */
public class PanelConsultar extends javax.swing.JPanel {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("LCPU");
    
    public PanelConsultar() {
        initComponents();
        table.setModel(new tabelModelc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jlConsultarBoton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Tipo de Documento", "No.Identificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jlConsultarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonConsultar.jpg"))); // NOI18N
        jlConsultarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jlConsultarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jlConsultarBoton)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlConsultarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultarBotonMouseClicked
        
        
        EmpleadoJpaController ejc = new EmpleadoJpaController(emf);
        List<Empleado> listEmpelado = ejc.findEmpleadoEntities();
        Empleado empleado = new Empleado();
        
        empleado = listEmpelado.get(table.getSelectedRow());
        
        PanelResultadosConsulta rc = new PanelResultadosConsulta(empleado);
        rc.setSize(883, 1000);
        
        this.setSize(1500, 1204);
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(rc);
    }//GEN-LAST:event_jlConsultarBotonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlConsultarBoton;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
  
    
    private class tabelModelc extends AbstractTableModel{
        
        EmpleadoJpaController ejc = new EmpleadoJpaController(emf);
        List<Empleado> listaempleado = ejc.findEmpleadoEntities();
        //List<Empleado> listaempleado = listaActivosEmpleado();
        
        @Override
        public int getRowCount() {
                return listaempleado.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int column) {
            switch(column){
                case 0: return "Nombre"; 
                case 1: return "Apellido";
                case 2: return "Tipo Documento"; 
                case 3: return "No. Identificación";
            }
            return "";
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            
            Empleado empleado = listaempleado.get(rowIndex);
            
            switch(columnIndex){
                case 0: return empleado.getNombres(); 
                case 1: return empleado.getApellidos();
                case 2: return empleado.getTipoDocumento(); 
                case 3: return empleado.getIdEmpleado();
            }
            return "";
        }
        
    }
    
//    public LinkedList<Empleado> listaActivosEmpleado(){
//        
//        EmpleadoJpaController ejc = new EmpleadoJpaController(emf);
//        List<Empleado> listaempleado = ejc.findEmpleadoEntities();
//        LinkedList<Empleado> listaEmpladosA= new LinkedList<>();
//        
//        for (Empleado listaE : listaempleado) {
//            
//            if(listaE.getEstado().equals("Activo")){
//                listaEmpladosA.add(listaE);
//            }
//        }
//        return listaEmpladosA;
//    }
}
