/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFacturasPagos;

import ClasesTablas.Factura;
import ClasesTablas.ItemsDeFactura;
import ClasesTablas.Pagos;
import ControladorClasesTablas.FacturaJpaController;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LLano
 */
public class FacturasConsultar extends javax.swing.JPanel {

    /**
     * Creates new form FacturasModificar
     */
    public FacturasConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.Factura", "Estado", "Hora_pago", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonConsultar.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(303, 303, 303))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            
       
        FacturarResultadosConsulta rm = new FacturarResultadosConsulta();
        rm.setSize(752, 1000);  
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("LCPU");
        FacturaJpaController daof = new FacturaJpaController(emf);        
        int a = Integer.parseInt(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(),0)));
        Factura factura = daof.findFactura(a);  
        
        Set<ItemsDeFactura> SetItems = factura.getItemsDeFacturaSet();  
        List<ItemsDeFactura> facturaDeItems = new ArrayList<>(SetItems);
                
        Object fila[][]=new Object[facturaDeItems.size()][3];        
        for (int i = 0; i < facturaDeItems.size(); i++) {         
            fila[i][0]=facturaDeItems.get(i).getCantidad();
            fila[i][1]=facturaDeItems.get(i).getItemsDeFacturaPK().getNombre();           
            fila[i][2]=facturaDeItems.get(i).getPrecio();                  
            }
        
        String columna[]=new String[]{"Cantidad","Producto","Precio"};        
       
        
        Set<Pagos> SetPagos = factura.getPagosSet();  
        List<Pagos> PagosFactura = new ArrayList<>(SetPagos);
        
        Object fila2[][]=new Object[PagosFactura.size()][4];        
        for (int i = 0; i < PagosFactura.size(); i++) {         
            fila2[i][0]=PagosFactura.get(i).getPagosPK().getIdPago();
            fila2[i][1]=PagosFactura.get(i).getTipo();           
            fila2[i][2]=PagosFactura.get(i).getValor();
            fila2[i][3]=PagosFactura.get(i).getCedulaCliente();
            }
        
        String columna2[] = new String[]{"Id","Tipo","Valor","Cedula Cliente"};        
        emf.close();        
        
        
        DefaultTableModel ModeloItems = new DefaultTableModel(fila,columna);
        DefaultTableModel ModeloPagos = new DefaultTableModel(fila2,columna2);
        rm.jTable1.setModel(ModeloItems);
        rm.jTable2.setModel(ModeloPagos);
        rm.jTextField1.setText(String.valueOf(factura.getValorTotal()));
        rm.jTextField2.setText(factura.getIdFactura().toString());                         
        
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        
       
            
       
        
        this.add(rm);
        
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
